name: Release

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.11.0
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Make sure the release step uses its own credentials:
        # https://github.com/cycjimmy/semantic-release-action#private-packages
        persist-credentials: false
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "latest"
        cache: 'npm'

    - name: Cache Gradle
      uses: burrunan/gradle-cache-action@v1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew clean generateReleaseFeatureMetadata build

    - name: Install dependencies
      run: npm install

    - name: Upload Patches Artifact
      uses: actions/upload-artifact@v4
      with:
        name: revanced-patches-output
        # Dùng ký tự ** để quét file .jar và .rvp ở mọi thư mục con, tránh việc sai lệch đường dẫn
        path: |
          **/*.apk

